# Generated by Django 2.1.1 on 2018-09-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OS_Info_Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(auto_now_add=True, help_text='记录时间')),
                ('cpu', models.FloatField(help_text='CPU1利用率')),
                ('cpu_1', models.FloatField(help_text='CPU1分钟负载')),
                ('cpu_5', models.FloatField(help_text='CPU5分钟负载')),
                ('cpu_15', models.FloatField(help_text='CPU15分钟负载')),
                ('memory', models.IntegerField(help_text='内存')),
                ('swap', models.FloatField(help_text='交换空间')),
                ('netin', models.BigIntegerField(help_text='下行流量')),
                ('netout', models.BigIntegerField(help_text='上行流量')),
                ('user', models.CharField(help_text='登录用户', max_length=20)),
            ],
            options={
                'verbose_name': '静态记录',
                'db_table': 'tb_os_static',
            },
        ),
        migrations.CreateModel(
            name='Os_Info_Tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(auto_now_add=True, help_text='记录时间')),
                ('os_version', models.CharField(help_text='系统版本', max_length=30, null=True)),
                ('cpu_total', models.IntegerField(help_text='CPU个数')),
                ('mem_total', models.CharField(help_text='总内存', max_length=30, null=True)),
                ('uptime', models.CharField(help_text='系统启动时间', max_length=20)),
                ('disk_root', models.CharField(help_text='硬盘总量', max_length=20)),
                ('disk_root_p', models.CharField(help_text='硬盘使用率', max_length=20)),
                ('disk_root_f', models.CharField(help_text='硬盘可用量', max_length=20)),
                ('disk_root_u', models.CharField(help_text='硬盘使用量', max_length=20)),
                ('disk_data', models.CharField(help_text='外挂硬盘总量', max_length=20)),
                ('disk_data_p', models.CharField(help_text='外挂硬盘使用率', max_length=20)),
                ('disk_data_f', models.CharField(help_text='外挂硬盘可用量', max_length=20)),
                ('disk_data_u', models.CharField(help_text='外挂硬盘使用量', max_length=20)),
                ('login_num', models.IntegerField(help_text='当前登录用户数')),
                ('proc_num', models.IntegerField(help_text='进程数')),
                ('net_conn', models.IntegerField(help_text='当前连接数')),
                ('ssh_status', models.CharField(help_text='SSH状态', max_length=5)),
                ('netin', models.BigIntegerField(help_text='流量下行')),
                ('netout', models.BigIntegerField(help_text='流量上行')),
            ],
            options={
                'verbose_name': '系统临时信息存储',
                'db_table': 'tb_os_info',
            },
        ),
    ]
