"""
Django settings for eoms project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# 用户关闭浏览器是否记住用户sessions
#SESSION_EXPIRE_AT_BROWSER_CLOSE=False
LOGIN_URL = '/login/'

ROOT_URLCONF = 'eoms.urls'
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*!e*nv(a9+jw_+1ua6*cb*!v_*i09o6_2$6=nfb-0*4!)@nj53'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gorgeous',
    'django_crontab',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    "gorgeous.time_middleware.my_middelwares",
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eoms.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
"default": {
    "ENGINE":   "django.db.backends.mysql",
    "HOST":     "127.0.0.1",
    "PORT":     3306,
    "NAME":     "demo",
    "USER":     "root",
    "PASSWORD": "flzx3qc",

}

}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)

# Log Config
LOG_DIR = os.path.join(BASE_DIR, 'logs')
LOG_FILE = "eoms.log"
LOG_LEVEL = "debug"

LOGGING = {
    'version':                  1,
    'disable_existing_loggers': False,  # 是否禁用已经存在的日志器
    'formatters':               {  # 日志信息显示的格式
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(lineno)d %(message)s'
        },
        'simple':  {
            'format': '%(levelname)s %(module)s %(lineno)d %(message)s'
        },
    },
    'filters':                  {  # 对日志进行过滤
        'require_debug_true': {  # django在debug模式下才输出日志
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers':                 {  # 日志处理方法
        'console': {  # 向终端中输出日志
            'level':     'INFO',
            'filters':   ['require_debug_true'],
            'class':     'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file':    {  # 向文件中输出日志
            'level':       'INFO',
            'class':       'logging.handlers.RotatingFileHandler',
            'filename':    os.path.join(os.path.dirname(BASE_DIR), "/home/kali/Desktop/-EOMS/logs/daily.log"),  # 日志文件的位置
            'maxBytes':    300 * 1024 * 1024,
            'backupCount': 10,
            'formatter':   'verbose'
        },
    },
    'loggers':                  {  # 日志器
        'django': {  # 定义了一个名为django的日志器
            'handlers':  ['console', 'file'],  # 可以同时向终端与文件中输出日志
            'propagate': True,  # 是否继续传递日志信息
            'level':     'INFO',  # 日志器接收的最低日志级别
        },
        
    }
    
}








# upload files
DOWNLOG_DIR = os.path.join(LOG_DIR,'downlogs')
UPLOADED_DIR = os.path.join(BASE_DIR,'bigdata')
CLIENT_DIR = os.path.join('/home/kali/Desktop/eoms/data/linkdood/data/update/predownload/')
# print(CLIENT_DIR)

# 定时任务
CRONJOBS = [
	# 每5分钟执行一次生成主页静态文件
	('*/5 * * * *', "vrvtools.to_django.insert_data",
	 '>> /home/kali/Desktop/eoms/logs/crontab.log')
]

# 解决crontab中文问题  定时任务
CRONTAB_COMMAND_PREFIX = 'LANG_ALL=zh_cn.UTF-8'

# redis 配置远程阿里云
CACHES = {
	"default":      {
		"BACKEND":  "django_redis.cache.RedisCache",
		"LOCATION": "redis://127.0.0.1:6379/0",
		"OPTIONS":  {
			"CLIENT_CLASS": "django_redis.client.DefaultClient",
		}
	},
	"session":      {
		"BACKEND":  "django_redis.cache.RedisCache",
		"LOCATION": "redis://127.0.0.1:6379/1",
		"OPTIONS":  {
			"CLIENT_CLASS": "django_redis.client.DefaultClient",
		}
	},
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"  # session存储位置为缓存指定为redis
SESSION_CACHE_ALIAS = "session"  # 指定为redis 上边的配置  一号库区

SESSION_COOKIE_AGE = 60 * 10000